### ISSUE TITLE
[RFC] React-admin v5

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/react-admin#9462]
## Rationale

It's been [a year and a half](https://github.com/marmelab/react-admin/releases/tag/v4.0.0) since version 4.0. The React ecosystem has evolved a lot since then, and we must accept a few breaking changes in the react-admin codebase to keep up-to-date. So we're starting the work on the next major version, react-admin v5.

The main constraint of this version is to be a **painless migration from v4**. The 3.0 to 4.0 migration was costly for many developers, we don't want to reiterate that. The migration should take at most a day on a moderate size admin app. 

## Breaking Changes

- [x] Bump React version to 18
- [x] Underline links by default (#9483)
- [x] Infer datagrid rowClick based on resource definition (#9466)
- [x] Enable dark theme by default, so that new admins have a theme switcher (#9479)
- [x] Remove injected props in `Admin` and `Layout` components (`layout`, `appBar`, `menu`, `error`, `catchAll`) (#9591)
- [x] Make all input widths consistent (#9704)
- [x] Replace `defaultProps` with default params values (#9586)
- [x] Remove `<Admin history>` prop and use react-router's Data Router (#9657)
- [x] Remove list's setFilters default debounce (#9682)
- [x] Drop support for IE (#9530)
- [x] Allow to set button size via theme (#9735)
- [x] Remove instances of `cloneElement` that we can replace with context
  - #9533
  - #9707
  - #9719
  - #9805
- [x] Update dependencies to their last major 
  - #9473
  - #9657
  - #9763
  - #9924
  - #9801
  - #9804
  - #9811
  - #9819
  - #9818
  - #9822
  - #9823
  - #9874
  - #9908
  - ~~#9812~~ (reverted in #9871 because it causes compilation problems)
- [x] Stricter TypeScript types 
  - #9644
  - #9741
  - #9743
  - #9760
  - #9761
  - #9790
  - #9795
  - #9797
- [x] Remove PropTypes (#9851)
- [x] Apply new prettier rules (#9874)

See the progress in the following milestones:
- [x] [5.0.0-alpha.0](https://github.com/marmelab/react-admin/milestone/290?closed=1)
- [x] [5.0.0-beta.0](https://github.com/marmelab/react-admin/milestone/304?closed=1)
- [x] [5.0.0-beta.1](https://github.com/marmelab/react-admin/milestone/309?closed=1)
- [x] [5.0.0-beta.2](https://github.com/marmelab/react-admin/milestone/311?closed=1)
- [x] [5.0.0-beta.3](https://github.com/marmelab/react-admin/milestone/312?closed=1)
- [x] [5.0.0-rc.0](https://github.com/marmelab/react-admin/milestone/313?closed=1)
- [x] [5.0.0-rc.1](https://github.com/marmelab/react-admin/milestone/315?closed=1)
- [ ] [5.0.0](https://github.com/marmelab/react-admin/milestone/316?closed=1)

## Out Of Scope

- Framework-agnostic library (to pave the way for Svelte Admin, Astro admin, etc)
- Turn react-admin into a server-side rendering framework. We believe that SPAs are still the best architecture for admins. 

## Roadmap

We intend to release version 5 in early 2024. 

There won't be any other major version until 2026, so we must include in v5 all the breaking changes that are necessary to last until then. 

Version 5 is now the primary focus of the core team, so there won't be any new minor until we release v5. [V4.16](https://github.com/marmelab/react-admin/releases/tag/v4.16.0) is the last minor release in the 4.x branch. Every new feature will be added to the `next` branch, which will become react-admin v5. 

https://github.com/github/release-radar

## We need your feedback

Are there other breaking changes that you think should make it to v5? Please give us your feedback by commenting on this issue. 

Note: Please don't comment with feature requests that don't imply any breaking change. For those, simply open a new issue.

**Comment by quentin-decre** [comment]
I am aligned with the changes and what is out of scope.  Useful parts for us :
- Dom recycling for regular datagrid, or datagridAg with server loading
- simpler RBAC (in the data provider), we will have to implement this in January
- better support for Graphql (we use hasura), so that our data provider gets simpler.

Thanks for your very nice work !

**Comment by panfiva** [comment]
there are a few tickets that mentioned implementing them in v5. one of them is moving title to context. that would be a good change. https://github.com/marmelab/react-admin/issues/8872

**Comment by panfiva** [comment]
Change how `setFilters` work to make it more convenient to use:
- Split `setFilters` into `setFilters` and `setDisplayedFilters` - most of the time, I either need to update filters or update displayed filters, but not both
- Each function show allow receive the value itself, or a function  `(current_values)=>current_values` (similar to `setState`):
   - Besides improving usability, also will allow running `setFilter` statements without worry of using outdated filters inside useEffect.
   - This is similar to `setState` when we want to increment current value by one twice: Instead of running `setState(n+1); setState(n+1)`, we need to run `setState((v)=v+1); setState((v)=v+1);` I know that this example is over-simplified and no-one would write something like that; however I've been throw situations where calling `setFilters` (and `setState`) suffered concurrency issues. 
- Create `setFilter(filter_name, value | (value)=>newValue )` and `clearFilter(filter_name)` functions to control individual filters.

**Comment by KilianB** [comment]
> * could you please elaborate more on this one `Remove cloneElement in inputs by introducing an input name prefix context`. maybe an example?

As far as I can remember `cloneElement` is used to augment the path of nested form controls e.g. inside `ReferenceManyInput` to have a unique location for the purpose of react-hook-forms `useController` . One thing that cost me hours was the inability to nest layout elements inside certain components as they would expect the direct children to be the input/field components. This would be fixed with this change right?

Does the rework of the stricter Typescript types include generics for input components? Those would save a lot of issues and if registered Resources could be types, this help a lot during development

**Comment by panfiva** [comment]
Evaluate migration to `future.v7_relativeSplatPath`  flag that react-router team implemented to address breaking change that they made in 6.19.0.

https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/CHANGELOG.md#6210

**Comment by djhi** [comment]
> As far as I can remember `cloneElement` is used to augment the path of nested form controls e.g. inside `ReferenceManyInput` to have a unique location for the purpose of react-hook-forms `useController` . One thing that cost me hours was the inability to nest layout elements inside certain components as they would expect the direct children to be the input/field components. This would be fixed with this change right?

Yes, that's the plan. Some high level components might still inspect children though, Datagrid for instance.

> Does the rework of the stricter Typescript types include generics for input components? Those would save a lot of issues and if registered Resources could be types, this help a lot during development

Yes, we have plans for this. Not necessarily in v5.0 though

**Comment by milutinovici** [comment]
Consider switching to
https://github.com/TanStack/router?

**Comment by fzaninotto** [comment]
> Consider switching to https://github.com/TanStack/router?

Why would we want to do that? What problems does react-router have that tanstack router would solve?

**Comment by milutinovici** [comment]
This blog post explains all the advantages

https://swizec.com/blog/tanstack-router-modern-react-for-the-rest-of-us/

**Comment by fzaninotto** [comment]
@milutinovici I don't understand the pain points that TanStack router would solve *in react-admin apps*.

**Comment by DiegoAndai** [comment]
Hey! [Material UI has announced its v6 release for 2024](https://mui.com/blog/2023-material-ui-v6-and-beyond/) focusing on a new style engine: https://github.com/mui/material-ui/issues/38137

The timeline (kind of) aligns with React-admin's v5, and I thought you might be interested, especially given there won't be any other major version until 2026.

Let us know! 😊

**Comment by fzaninotto** [comment]
They announce v6 for Q2 2024... Which is late for us. It could mean up to 7 months without a new minor release for react-admin, which is too much. Besides, we'll need to wait until the dust settles e bit before using it, so I don't see our development on the new MUI starting before fall 24. 

IMO, their schedule isn't compatible with ours, and react-admin v5 won't use MUI v6.

**Comment by davidhenley** [comment]
> Make all input width 100% by default (to make [this page](https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-input--all-inputs) nicer)

Finally!

**Comment by smeng9** [comment]
I suggest we also update the documentation website to show the documentation for a specific branch (e.g. next as unreleased) in the dropdown selection before v5 is officially released. After v5 release we can then decide whether to remove that item from the dropdown list.

I propose we can do something like ESLint documentation in https://github.com/eslint/eslint/pull/18139 
<img width="312" alt="Screenshot 2024-02-29 at 10 00 10 AM" src="https://github.com/marmelab/react-admin/assets/38666763/455ffce9-830b-4d3a-a745-9dba190c7528">

This feature request may be a breaking change for the current ci pipeline, but it will be particularly helpful for early adopters to try and give feedbacks without the need to build and serve the documentation locally. During the upgrade cycle from v3 to v4 we don't have such thing for a better developer experience and a smoother migration.

**Comment by smeng9** [comment]
Hi @fzaninotto any plans on updating the docs on the https://marmelab.com/react-admin/documentation.html for v5 alpha?

**Comment by fzaninotto** [comment]
@smeng9 No, we don't have such plans. The docs on the react-admin website will only be updated when we release v5 stable. In the meantime, you can browse the V5 docs at https://github.com/marmelab/react-admin/tree/next/docs.

**Comment by MohammedFaragallah** [comment]
Hello thank you for all your hard and amazing work

I see that you're planning on updating dependencies to their last major does that include `date-fns`? I can work on a PR.

**Comment by fzaninotto** [comment]
@MohammedFaragallah yes, good idea! PR welcome.

**Comment by lefuturiste** [comment]
On the issue of dynamic title #5893
If I understand correctly, the goal is to automatically update the document title from the title in TitlePortal.
The PR that implemented this behaviour #6119 was reverted in #6357 because of an hidden breaking changes.
So may be the v5 is the right time to re-introduce this patch/PR?

**Comment by MohammedFaragallah** [comment]
@fzaninotto what do you think about updating these packages

- [ ] react-dropzone v12 to v14
- [ ] clsx v1 to v2
- [ ] query-string v7 to v9
- [ ] react-i18next v13 to v14
- [ ] react-error-boundary v3 to v4

**Comment by fzaninotto** [comment]
@MohammedFaragallah I'm all for it, please feel free to open one PR per dependency

**Comment by fzaninotto** [comment]
> On the issue of dynamic title #5893 If I understand correctly, the goal is to automatically update the document title from the title in TitlePortal. The PR that implemented this behaviour #6119 was reverted in #6357 because of an hidden breaking changes. So may be the v5 is the right time to re-introduce this patch/PR?

Yes, it's a good time. Would you like to try and solve the issue?

**Comment by fzaninotto** [comment]
@tauqeer-trailfive Do you know when it is supposed to be released?

**Comment by tauqeer-trailfive** [comment]
No it don't know but its beta release week ago.

**Comment by tauqeer-trailfive** [comment]
just wondering, we have to upgrade our code bases also if you're doing this.

**Comment by fzaninotto** [comment]
We hope to release react-admin v5 not too far in the future (ideally in a month from now). I doubt React 19 will be up at that time. 

Also, which react 19 features do you think would benefit to react-admin ?

**Comment by MohammedFaragallah** [comment]
what do you think about adding generics to infer the returned props types from sanitize rest functions?

something like this

``` ts
const sanitizeRestProps = <T extends Record<string, unknown>>({
    record,
    resource,
    initialValues,
    translate,
    ...rest
}: T) => rest;
```

`rest` here is typed `Omit<T, "record" | "resource" | "initialValues" | "translate">` which is far more useful than the previous `any`

I can work on a PR

**Comment by fzaninotto** [comment]
> what do you think about adding generics to infer the returned props types from sanitize rest functions?
> 
> something like this
> 
> ```ts
> const sanitizeRestProps = <T extends Record<string, unknown>>({
>     record,
>     resource,
>     initialValues,
>     translate,
>     ...rest
> }: T) => rest;
> ```
> 
> `rest` here is typed `Omit<T, "record" | "resource" | "initialValues" | "translate">` which is far more useful than the previous `any`
> 
> I can work on a PR

I don't see the interest for the end user, and I don't see it as a breaking change. We do a v5 especially for breaking changes. So while your suggestion might bring some improvements to the core team, it won't be a priority.

**Comment by MohammedFaragallah** [comment]
> I don't see the interest for the end user, and I don't see it as a breaking change.

I disagree i just noticed this while writing a custom input and I thought my experience would have been better if I had the returned props types and also if the sanitizers were exported instead of having to copy-paste them and keep them in sync

I understand if this is not a priority RN though 🤝

**Comment by zhu-hong** [comment]
when i looked the `Update dependencies to their last major`, i know react-admin is a have aspirations's framework

**Comment by sixers** [comment]
When can we expect [5.0.0-beta.1](https://github.com/marmelab/react-admin/milestone/309?closed=1) release?

**Comment by fzaninotto** [comment]
> When can we expect [5.0.0-beta.1](https://github.com/marmelab/react-admin/milestone/309?closed=1) release?

Today! https://github.com/marmelab/react-admin/releases/tag/v5.0.0-beta.1

**Comment by sixers** [comment]
@fzaninotto I noticed that RA v5 still shows a few errors when `strict: true`, it only works with `strict: false` and `strictNullChecks`: true. Is it possible to go full `strict` mode before final v5 release? Looks like you're extremely close to that.

**Comment by fzaninotto** [comment]
> @fzaninotto I noticed that RA v5 still shows a few TS errors when `strict: true`, it only works with `strict: false` and `strictNullChecks: true`. Is it possible to go full `strict` mode before final v5 release? Looks like you're extremely close to achieving that.

This is not in our target for v5. However, if you want to submit a PR and it's small enough to be merged quickly, we'll take a look at it.

**Comment by fzaninotto** [comment]
5.0.0-beta.2 is out: https://github.com/marmelab/react-admin/releases/tag/v5.0.0-beta.2

**Comment by fzaninotto** [comment]
5.0.0-beta.3 is out: https://github.com/marmelab/react-admin/releases/tag/v5.0.0-beta.3

**Comment by kztmk** [comment]
I tried V5.0.0-rc.0:

node: v20.12.2
macOSX 14.5

How can I resolve this?

>>>
❯ npm init react-admin@next my-project
Need to install the following packages:
create-react-admin@5.0.0-rc.0
Ok to proceed? (y)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

  ERROR  Cannot read properties of null (reading 'useReducer')

 /Users/username/.npm/_npx/f03da9ea442c06c6/node_modules/create-react-admin/node_modules/react/cjs/react.development
 .js:1626:21

 1623: }
 1624: function useReducer(reducer, initialArg, init) {
 1625:   var dispatcher = resolveDispatcher();
 1626:   return dispatcher.useReducer(reducer, initialArg, init);
 1627: }
 1628: function useRef(initialValue) {
 1629:   var dispatcher = resolveDispatcher();

**Comment by fzaninotto** [comment]
@kztmk reproduced, thanks. We'll soon release a fix.

**Comment by fzaninotto** [comment]
v5.0.0-rc.1 is out. It fixes `create-react-admin`. 

https://github.com/marmelab/react-admin/releases/tag/v5.0.0-rc.1

There is still a problem if you choose FakeRest as your data provider because of a typo in a dependency list, fixed in 795cd74f628071a4200eea79bb856b5654e2653d but not part of rc.1.

**Comment by fzaninotto** [comment]
React-admin v5 is out! https://github.com/marmelab/react-admin/releases/tag/v5.0.0

**Comment by franz101** [comment]
what's the plan / road map for reactadmin 6?

**Comment by MohammedFaragallah** [comment]
> @franz101 what's the need for react-admin v6?

Pushing react-admin to be more headless would be amazing 

Custom routers for example

**Comment by kztmk** [comment]
add @tiptap editor, please.

**Comment by fzaninotto** [comment]
What's the business need for another router? 
About TipTap, we don't need a v6 for that, it can be done in another package on top of v5.

**Comment by franz101** [comment]
> [@franz101](https://github.com/franz101) what's the need for react-admin v6?

- make the docs more ai readable
- give cursor rules
- support nosql dbs
- allow deployment on Cloudflare Pages  + d1
- next js support
- openapi swagger docs

**Comment by fzaninotto** [comment]
@franz101 None of these require breaking changes, so I don't see why we'd need a v6. React-admin pushes new features every month through minor versions (see our [releases page](https://github.com/marmelab/react-admin/releases)).
